-- Create mvp_topics table (Global Megatopics)
create table public.mvp_topics (
  id bigint generated by default as identity primary key,
  date date not null default current_date,
  title text not null,
  summary text,
  thumbnail_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create countries table (If not exists, or use mvp_countries)
-- Assuming countries table is static and shared, but to be safe let's use mvp_countries or just check existence.
-- For MVP safety, let's use mvp_countries too.
create table public.mvp_countries (
  code text primary key, -- e.g. 'US', 'KR', 'JP'
  name text not null,
  flag_emoji text
);

-- Seed countries (G10 + others)
insert into public.mvp_countries (code, name, flag_emoji) values
('US', 'United States', '🇺🇸'),
('GB', 'United Kingdom', '🇬🇧'),
('FR', 'France', '🇫🇷'),
('DE', 'Germany', '🇩🇪'),
('IT', 'Italy', '🇮🇹'),
('CA', 'Canada', '🇨🇦'),
('JP', 'Japan', '🇯🇵'),
('KR', 'South Korea', '🇰🇷'),
('CN', 'China', '🇨🇳'),
('RU', 'Russia', '🇷🇺')
on conflict (code) do nothing;

-- Create articles table (Optional for now, but good for lineage)
create table public.mvp_articles (
  id bigint generated by default as identity primary key,
  url text not null unique,
  title text not null,
  source text,
  country_code text references public.mvp_countries(code),
  published_at timestamp with time zone,
  stance text check (stance in ('supportive', 'factual', 'critical')),
  topic_id bigint references public.mvp_topics(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create mvp_topic_country_stats table (Aggregated stats for UI)
create table public.mvp_topic_country_stats (
  id bigint generated by default as identity primary key,
  topic_id bigint references public.mvp_topics(id) not null,
  country_code text references public.mvp_countries(code) not null,
  supportive_count int default 0,
  factual_count int default 0,
  critical_count int default 0,
  summary text, -- Country-specific summary of the topic
  unique(topic_id, country_code)
);
